#!/usr/bin/env python3
"""
stylegen.py - Generate styles/custom.css from optional overrides in style/.

Conventions (everything is "if present use, if not ignore"):
  style/fonts/title.(ttf|otf)   font for titles/headings
  style/fonts/body.(ttf|otf)    font for body text
      - exactly ONE font file with any name -> used for BOTH roles
  style/palette.json            color overrides, any subset of:
      { "primary": "#RRGGBB", "secondary": "...", "ink": "...",
        "page_bg": "...", "tint": "..." }

Always writes styles/custom.css (empty stub when nothing is present), so pages
can link it unconditionally after page.css. Overrides win by CSS cascade.
Fails loudly on a malformed palette.json or bad color value.

Usage: python scripts/stylegen.py   (run from the project root)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "style" / "fonts"
PALETTE = ROOT / "style" / "palette.json"
OUT = ROOT / "styles" / "custom.css"

PALETTE_KEYS = ("primary", "secondary", "ink", "page_bg", "tint")
HEX = re.compile(r"^#[0-9a-fA-F]{6}$")


def find_fonts():
    """Return (title_font, body_font) Paths or Nones."""
    if not FONT_DIR.is_dir():
        return None, None
    fonts = sorted(p for p in FONT_DIR.iterdir()
                   if p.suffix.lower() in (".ttf", ".otf") and p.is_file())
    if not fonts:
        return None, None
    title = next((p for p in fonts if p.stem.lower() == "title"), None)
    body = next((p for p in fonts if p.stem.lower() == "body"), None)
    if not title and not body and len(fonts) == 1:
        return fonts[0], fonts[0]          # one font -> both roles
    if title and not body and len(fonts) == 1:
        return title, None
    if body and not title and len(fonts) == 1:
        return None, body
    return title, body


def font_face(role, path):
    fmt = "opentype" if path.suffix.lower() == ".otf" else "truetype"
    rel = f"../style/fonts/{path.name}"     # custom.css lives in styles/
    return (f"@font-face {{ font-family: 'Custom {role.title()}'; "
            f"src: url('{rel}') format('{fmt}'); }}\n")


def main():
    lines = ["/* GENERATED by scripts/stylegen.py - do not edit. "
             "Overrides from style/fonts and style/palette.json. */\n"]
    root_vars = []

    title_f, body_f = find_fonts()
    if title_f:
        lines.append(font_face("title", title_f))
        root_vars.append("  --font-title: 'Custom Title', Georgia, serif;")
        print(f"font: title  <- style/fonts/{title_f.name}")
    if body_f:
        lines.append(font_face("body", body_f))
        root_vars.append("  --font-body: 'Custom Body', system-ui, sans-serif;")
        print(f"font: body   <- style/fonts/{body_f.name}")

    if PALETTE.is_file():
        try:
            pal = json.loads(PALETTE.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"STYLEGEN FAILED: style/palette.json is not valid JSON: {e}")
            sys.exit(1)
        unknown = [k for k in pal if k not in PALETTE_KEYS]
        if unknown:
            print(f"STYLEGEN FAILED: unknown palette key(s) {unknown}; "
                  f"allowed: {list(PALETTE_KEYS)}")
            sys.exit(1)
        for key in PALETTE_KEYS:
            if key in pal:
                val = str(pal[key])
                if not HEX.match(val):
                    print(f"STYLEGEN FAILED: palette '{key}' must be #RRGGBB, got '{val}'")
                    sys.exit(1)
                root_vars.append(f"  --{key.replace('_', '-')}: {val};")
                print(f"palette: {key:9s} <- {val}")

    if root_vars:
        lines.append(":root {\n" + "\n".join(root_vars) + "\n}\n")
    else:
        lines.append("/* no overrides present - defaults from page.css apply */\n")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}"
          + ("" if root_vars else "  (empty stub)"))


if __name__ == "__main__":
    main()
